name: CI/CD - Pruebas y Despliegue

# Se ejecuta automáticamente cada vez que subimos código a la rama main
on:
  push:
    branches: [main]

jobs:

  # PASO 1: Corre las pruebas para verificar que el código funciona bien
  pruebas:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest
    steps:
      # Descarga el código del repositorio
      - uses: actions/checkout@v4

      # Instala Node.js versión 20
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instala las dependencias del proyecto
      - run: npm install

      # Ejecuta las pruebas con Jest
      - run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  # PASO 2: Solo despliega en Vercel si las pruebas del paso anterior pasaron
  despliegue:
    name: Desplegar en Vercel
    runs-on: ubuntu-latest
    needs: pruebas
    steps:
      # Descarga el código del repositorio
      - uses: actions/checkout@v4

      # Instala la herramienta de Vercel
      - run: npm install -g vercel

      # Despliega la aplicación en producción
      - run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}